#!/usr/bin/env node
/**
 * MAISON Shop — Interactive Setup Wizard
 * Run with:  node setup.js
 */
const readline = require('readline');
const fs       = require('fs');
const path     = require('path');
const crypto   = require('crypto');
const { execSync } = require('child_process');

const ENV_PATH = path.join(__dirname, 'backend', '.env');
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

const ask = (q) => new Promise(res => rl.question(q, res));
const bold  = s => `\x1b[1m${s}\x1b[0m`;
const green = s => `\x1b[32m${s}\x1b[0m`;
const cyan  = s => `\x1b[36m${s}\x1b[0m`;
const red   = s => `\x1b[31m${s}\x1b[0m`;
const dim   = s => `\x1b[2m${s}\x1b[0m`;

async function main() {
  console.log('\n' + bold('═══════════════════════════════════════════'));
  console.log(bold('   MAISON Fashion Shop — Setup Wizard'));
  console.log(bold('═══════════════════════════════════════════') + '\n');

  // ── Step 1: MongoDB ──────────────────────────────────────
  console.log(bold('Step 1 of 3 — MongoDB Connection\n'));
  console.log('Choose your database:');
  console.log(`  ${cyan('1')}  MongoDB Atlas (free cloud — recommended)`);
  console.log(`  ${cyan('2')}  Local MongoDB (already installed on my machine)\n`);

  const dbChoice = (await ask('Enter 1 or 2: ')).trim();
  let mongoUri;

  if (dbChoice === '2') {
    const defaultUri = 'mongodb://localhost:27017/fashionshop';
    const input = await ask(`\nLocal URI ${dim(`[${defaultUri}]`)}: `);
    mongoUri = input.trim() || defaultUri;
    console.log(dim('\nMake sure mongod is running before starting the server.'));
  } else {
    console.log('\n' + dim('Get your Atlas URI:'));
    console.log(dim('  1. cloud.mongodb.com → create free account'));
    console.log(dim('  2. New Project → Build a Database → Free tier (M0)'));
    console.log(dim('  3. Database Access → Add user with password'));
    console.log(dim('  4. Network Access → Add IP → Allow from anywhere (0.0.0.0/0)'));
    console.log(dim('  5. Connect → Drivers → Copy connection string\n'));
    const uri = await ask('Paste your Atlas connection string: ');
    mongoUri = uri.trim().replace('<password>', () => {
      console.log(red('\n  ⚠  Replace <password> with your actual Atlas password in the .env file.\n'));
      return '<password>';
    });
    if (!mongoUri.includes('mongodb')) {
      console.log(red('\nThat doesn\'t look like a MongoDB URI. You can edit backend/.env manually.\n'));
      mongoUri = mongoUri || 'mongodb+srv://user:password@cluster.mongodb.net/fashionshop';
    }
  }

  // ── Step 2: Port ─────────────────────────────────────────
  console.log('\n' + bold('Step 2 of 3 — Server Port\n'));
  const portInput = await ask(`Backend port ${dim('[5000]')}: `);
  const port = portInput.trim() || '5000';

  // ── Step 3: JWT Secret ───────────────────────────────────
  console.log('\n' + bold('Step 3 of 3 — Security\n'));
  const autoSecret = crypto.randomBytes(48).toString('hex');
  const jwtInput   = await ask(`JWT secret ${dim('[auto-generate]')}: `);
  const jwtSecret  = jwtInput.trim() || autoSecret;
  if (!jwtInput.trim()) console.log(green('  ✓ Auto-generated a secure JWT secret'));

  // ── Write .env ───────────────────────────────────────────
  const env = `# Generated by setup.js on ${new Date().toISOString()}

# ── MongoDB ───────────────────────────────────────────────
MONGO_URI=${mongoUri}

# ── Server ────────────────────────────────────────────────
PORT=${port}
NODE_ENV=development

# ── Security ──────────────────────────────────────────────
JWT_SECRET=${jwtSecret}

# ── CORS ──────────────────────────────────────────────────
CORS_ORIGIN=http://localhost:3000
`;

  fs.writeFileSync(ENV_PATH, env);
  console.log(green(`\n✅  Saved backend/.env\n`));

  // ── Install deps? ────────────────────────────────────────
  const installAns = await ask('Install all dependencies now? (Y/n): ');
  if (!installAns.trim() || installAns.toLowerCase() === 'y') {
    console.log('\nInstalling backend dependencies…');
    try { execSync('cd backend && npm install', { stdio: 'inherit', cwd: __dirname }); } catch {}
    console.log('\nInstalling frontend dependencies…');
    try { execSync('cd frontend && npm install', { stdio: 'inherit', cwd: __dirname }); } catch {}
    console.log(green('\n✅  Dependencies installed'));
  }

  // ── Seed? ────────────────────────────────────────────────
  const seedAns = await ask('\nSeed the database with sample products? (Y/n): ');
  if (!seedAns.trim() || seedAns.toLowerCase() === 'y') {
    console.log('\nSeeding database…');
    try {
      execSync('cd backend && node seed.js', { stdio: 'inherit', cwd: __dirname });
    } catch (e) {
      console.log(red('\nSeeding failed — make sure your MongoDB is reachable first,'));
      console.log(red('then run:  npm run seed\n'));
    }
  }

  // ── Summary ──────────────────────────────────────────────
  console.log('\n' + bold('═══════════════════════════════════════════'));
  console.log(bold('   Setup Complete! 🎉'));
  console.log(bold('═══════════════════════════════════════════'));
  console.log(`
  Start the app:
    ${cyan('npm run dev')}         starts both frontend + backend

  Or start separately:
    ${cyan('cd backend && npm run dev')}   backend only
    ${cyan('cd frontend && npm start')}    frontend only

  URLs:
    Frontend  →  ${cyan('http://localhost:3000')}
    Backend   →  ${cyan(`http://localhost:${port}`)}
    Health    →  ${cyan(`http://localhost:${port}/api/health`)}

  Default logins (after seeding):
    Admin  →  admin@shop.com   / admin123
    User   →  jane@example.com / user123
`);

  rl.close();
}

main().catch(err => { console.error(err); rl.close(); process.exit(1); });
